# Generated by Django 5.2.8 on 2025-12-17 09:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificatScolarite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_certificat', models.CharField(blank=True, editable=False, max_length=10, unique=True, verbose_name='Numéro certificat')),
                ('nom_pere', models.CharField(default='Non spécifié', max_length=100, verbose_name='Nom du père')),
                ('nom_mere', models.CharField(default='Non spécifiée', max_length=100, verbose_name='Nom de la mère')),
                ('date_naissance', models.DateField(blank=True, help_text='Format: JJ/MM/AAAA', null=True, verbose_name='Date de naissance')),
                ('lieu_naissance', models.CharField(blank=True, help_text='Ville ou commune de naissance', max_length=150, null=True, verbose_name='Lieu de naissance')),
                ('quantite', models.PositiveIntegerField(default=1, help_text='Nombre de certificats demandés', verbose_name="Nombre d'exemplaires")),
                ('date_demande', models.DateTimeField(auto_now_add=True)),
                ('date_traitement', models.DateTimeField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('en_cours', 'En cours de traitement'), ('pret', 'Prêt à retirer')], default='en_attente', max_length=15, verbose_name='Statut de la demande')),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificats_scolarite', to='api.etudiant', verbose_name='Étudiant')),
            ],
            options={
                'verbose_name': 'Certificat de scolarité',
                'verbose_name_plural': 'Certificats de scolarité',
                'ordering': ['-date_demande'],
            },
        ),
    ]
