# Generated by Django 5.2.8 on 2025-12-17 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attestation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_attestation', models.CharField(blank=True, editable=False, max_length=12, unique=True)),
                ('type_attestation', models.CharField(choices=[('reussite', 'Attestation de Réussite'), ('inscription', 'Inscription'), ('langue', 'Langue Française d’Apprentissage'), ('duree', 'Durée de Formation'), ('fin_l3', 'Fin d’Études L3'), ('fin_m2', 'Fin d’Études M2')], max_length=20)),
                ('annee_scolaire', models.CharField(blank=True, max_length=9, null=True)),
                ('quantite', models.PositiveIntegerField(default=1)),
                ('prix', models.DecimalField(decimal_places=2, default=3000.0, max_digits=10, verbose_name='Prix unitaire (Ariary)')),
                ('total_paye', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('date_demande', models.DateTimeField(auto_now_add=True)),
                ('date_traitement', models.DateTimeField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('en_cours', 'En cours'), ('pret', 'Prêt à retirer')], default='en_attente', max_length=15)),
            ],
            options={
                'verbose_name': 'Attestation',
                'ordering': ['-date_demande'],
            },
        ),
    ]
