# Generated by Django 5.2.8 on 2025-12-17 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReleveNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_releve', models.CharField(blank=True, db_index=True, editable=False, max_length=10, unique=True)),
                ('demandes', models.JSONField(blank=True, default=list, help_text='Format: [{"niveau": "L1", "quantite": 2}]')),
                ('annee_universitaire', models.JSONField(blank=True, default=list, help_text='Format: [2022, 2023, 2024] ou ["2022", "2023"]', verbose_name='Années universitaires')),
                ('date_demande', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('date_traitement', models.DateTimeField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('en_cours', 'En cours'), ('pret', 'Prêt à retirer')], db_index=True, default='en_attente', max_length=15)),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes_releve', to='api.etudiant')),
            ],
            options={
                'verbose_name': 'Relevé de notes',
                'verbose_name_plural': 'Relevés de notes',
                'ordering': ['-date_demande'],
                'indexes': [models.Index(fields=['etudiant', 'statut'], name='releveNote__etudian_3683ea_idx'), models.Index(fields=['date_demande'], name='releveNote__date_de_292b85_idx')],
            },
        ),
    ]
